### ISSUE TITLE
Raspberry Pi have sent you a message

### ISSUE THREAD

**Issue by DeeJay** [davixdedem/Pi-Starlink#5]
[https://forums.raspberrypi.com/viewtopic.php?t=377580#p2258713](https://forums.raspberrypi.com/viewtopic.php?t=377580#p2258713)

Referring to [https://www.raspberrypi.com/trademark-rules/](https://www.raspberrypi.com/trademark-rules/)

**Comment by P33M** [comment]
The thread was deleted from our forums for obvious reasons. The content of the message is here:

>This looks super but I'm afraid I need to ask you not to use the trademarked Raspberry Pi logo as part of the project's branding - our logo is only for our own stuff. Please can you drop me a line ([comms@raspberrypi.com](mailto:comms@raspberrypi.com)) once you've changed it?
